blank_issues_enabled: true
contact_links:
  - name: 赞助通道
    url: https://afdian.net/a/Melon_Studio
    about: 前往爱发电赞助 Hot HMCL。
  - name: 其他反馈
    url: https://github.com/Melon-Studio/Hot-HMCL/discussions/new/choose
    about: 通过 Discussions 反馈其他问题。
